name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.8.2
  postgres: ^2.6.1
  shelf: ^1.4.1
  shelf_modular: ^2.1.0
  shelf_swagger_ui: ^1.0.0+2

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.21.0
